# simple.yaml

app:
  name: my-app
  version: 1.0.0
  environment: development

database:
  host: localhost
  port: 5432
  username: admin
  password: secret

features:
  logging: true
  authentication: true
  caching: false
