apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb-demo
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017  # You can choose any free port >30000


