apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  labels:
    app: nginx-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: asia-south1-docker.pkg.dev/test-kumar-makala/nginx-repo/nginx-demo:v1
        ports:
        - containerPort: 80
