apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: databases
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32001   # <-- use a free port
      protocol: TCP
