apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: databases
type: Opaque
stringData:
  POSTGRES_USER: priii
  POSTGRES_PASSWORD: MyStrongPassword123!
  POSTGRES_DB: mydatabase
