apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  type: LoadBalancer # Exposes your application externally via a Google Cloud Load Balancer
  ports:
  - protocol: TCP
    port: 80 # External port
    targetPort: 8000 # Internal container port
