apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: asia-south1-docker.pkg.dev/projectid-test-teraform-vm/fastapi-repo/api2:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend2-svc
spec:
  selector:
    app: backend2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
