name: Deploy Backend to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: test-kumar-makala
  CLUSTER_NAME: backend-cluster
  GKE_ZONE: us-central1-a
  DEPLOYMENT_NAME: backend-shailu-deployment
  IMAGE: gcr.io/test-kumar-makala/backend-shailu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker gcr.io --quiet

      - name: Build and push Docker image
        run: |
          cd backend-app
          docker build -t $IMAGE:$GITHUB_SHA .
          docker push $IMAGE:$GITHUB_SHA

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $GKE_ZONE --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/$DEPLOYMENT_NAME backend=$IMAGE:$GITHUB_SHA
          kubectl rollout status deployment/$DEPLOYMENT_NAME
