apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP   # 👈 Internal only (not accessible from outside)
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
